### ISSUE TITLE
DV file error on ImgSequence value > 2

### ISSUE THREAD

**Issue by delnatan** [tlambert03/mrc#3]
* mrc version: 0.2.0
* Python version: 3.9.10
* Operating System:MacOS Monterey 12.2.1

### Description
Got a `KeyError: 4` while opening a DeltaVision file from the Header lazy property `sequence_order`

### What I Did
`f = DVFile("./20220314_Unstim_002_R3D.dv")`

```
    291 @property
    292 def sequence_order(self) -> str:
    293     # note, these are reversed from the header readme,
   (...)
    296         # invalid value, use 0 instead
    297         # return "CTZ" 
--> 298     return {
    299         0: "CTZ",
    300         1: "TZC",
    301         2: "TCZ",
    302     }[self.img_seq]

KeyError: 4
```

A while ago I had acquired an Mrc.py (which opened this DeltaVision file just fine) that was distributed with the UCSF Priism and it seems that this is handled by checking if the ImgSequence value is >2, then it gets assigned a default value of 0 (using "CTZ" ordering).

Can we add:
`if self.img_seq > 2:
  return "CTZ"` to the lazy property `sequence_order`?

Thanks!

**Comment by tlambert03** [comment]
sure, can do.  thanks

**Comment by tlambert03** [comment]
actually, before I merge #4, would be curious to know if changing that line to `}.get(self.img_seq, "CTZ")` works for your file?  or if more is going to be needed...

**Comment by delnatan** [comment]
Thanks! for that specific instance using DVFile works fine.
But now I'm trying to open it via napari-dv but now the array size has a wrong Nz. Is DVFile used in the napari-dv plugin? or does it use the legacy API?

**Comment by tlambert03** [comment]
looks like it's using the old API.  however, I contributed a [DV reader to aicsimageio](https://github.com/AllenCellModeling/aicsimageio/blob/main/aicsimageio/readers/dv_reader.py) that does use the new API (which is kind of why I made the new one).  So maybe if you install [napari-aicsimageio](https://github.com/AllenCellModeling/napari-aicsimageio)?

**Comment by delnatan** [comment]
ah ok! thanks! will try that

**Comment by tlambert03** [comment]
(I can also update napari-dv to use the new one... but I've generally been trying to unify my stuff in aicsimageio moving forward.  it's built well and has good general file support)

**Comment by delnatan** [comment]
I agree, and it looks like napari-aicsimageio works fine for opening these DeltaVision files!
Thanks again for your help

**Comment by tlambert03** [comment]
fyi, napari-dv >= 0.3.0 will also now use the new API, and includes this fix.
